version: "3"

services:
  app:
    container_name: application
    image: application:latest
    build: ./app
    ports:
    - target: 5000
      protocol: tcp

  nginx:
    image: nginx:latest
    ports:
    - target: 8081
      published: 8081
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf