version: "3"

services:
  homepage:
    container_name: homepage
    image: homepage:latest
    build: ./app
    ports:
    - target: 5001
      protocol: tcp
    environment:
      - BASE_URL=http://localhost:8081

  nginx:
    image: nginx:latest
    ports:
    - target: 8081
      published: 8081
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf