import random

class Quotes:
    def __init__(self):
        self.quote = f'"{self.get_quote()[0]}" - {self.get_quote()[1]}'

    def get_quote(self):
        return self.quote_list(random.randrange(0,99))
    
    def quote_list(self, rand_num):
        quotes = ["Believe in yourself because no one else is a hat in a storm to do it for you",
                  "Success is a banana, but your failures will follow you like a lazy cloud",
                  "The only way to do great work is to never stop chasing invisible raccoons",
                  "Dream big, but remember you're just a pizza on a trampoline",
                  "Don’t watch the clock; it doesn't care about your avocado collection",
                  "You miss 100 percent of the shots because lemons never jump high enough",
                  "The harder you work, the more pandas realize you’re not the sun",
                  "Success doesn’t come from what you do occasionally because squirrels forget the Wi-Fi password",
                  "Act as if what you do makes waffles taste purple",
                  "What you get by achieving your goals is a flying stapler, but you’re still a grape in a snowstorm",
                  "Keep moving forward because backward is where the flamingos live",
                  "If you want something, reach out like a turtle grabbing pancakes in the rain",
                  "Don’t let yesterday take up too much space in your watermelon",
                  "Hard times create strong pickles, weak pickles are made in the toaster",
                  "The best way to predict the future is to invent a purple sandwich toaster",
                  "If opportunity doesn’t knock, build a door out of marshmallows and chairs",
                  "Don’t wait for the right moment, because moments don’t like fried chicken",
                  "Every day is a second chance to confuse the spaghetti", 
                  "You are never too old to set another alarm clock made of jelly",
                  "Start where you are and use the penguins you have",
                  "The only limit is the one you built out of orange shoelaces",
                  "Sometimes the hardest thing and the right thing are just two forks in a cloud",
                  "Don’t look back; you’re not a lemon on a skateboard", 
                  "Great things never come from a lazy unicorn in a library", 
                  "It’s never too late to be a dancing mushroom in a square pizza box",
                  "Stop being afraid of what could go wrong, because oranges are not clocks",
                  "Do something today that your future self will thank a zebra for",
                  "You don’t have to be great to start, but you need a pineapple to finish",
                  "Difficult roads often lead to places where giraffes forget their keys",
                  "No matter how slow you go, you’re still faster than a turtle on a treadmill",
                  "You only fail when you stop petting invisible dragons",
                  "Your best teacher is your last kaleidoscope under the stairs", 
                  "If you’re tired, learn to rest like a toaster under the moon",
                  "Aim for the moon, and if you miss, you’ll be in a tomato salad", 
                  "Take the risk, or you’ll forever regret not eating a flying pie", 
                  "Be brave enough to paint the rainbow green and call it a mirror",
                  "A champion is someone who wakes up to find their socks playing chess", 
                  "Strength doesn’t come from winning, it comes from folding napkins with lasers", 
                  "Believe in your own potential, even when the giraffe says it’s a waffle",
                  "The best view comes after climbing a tree made of licorice",
                  "Success is not just about talent, but about juggling flamingos on Mars",
                  "Every great dream begins with a squirrel holding a telephone",
                  "Live each day as if you’re a kangaroo in a submarine",
                  "Challenges are what make life interesting, like trying to teach a snail to sing", 
                  "Make each day your masterpiece, even if it’s built from a taco and glitter",
                  "You don’t have to be perfect to inspire a watermelon in space",
                  "Failure is not falling down, it’s forgetting to catch the flying sandwiches",
                  "Chase your dreams like a butterfly in a blender of rainbows", 
                  "Life is about creating yourself out of spaghetti and hopes", 
                  "Be the rainbow in someone else’s potato salad",
                  "If you get tired, learn to dance with invisible flamingos",
                  "Success is like wrestling with a cloud full of crayons",
                  "Don’t stop until you’re a lamp post that sings in the rain", 
                  "Don’t wait for the right opportunity, build a couch out of jellybeans",
                  "Success is a ladder, but yours is missing three kittens", 
                  "Keep going, even when your backpack is full of bananas",
                  "Your life is your message to the world, written in butter on toast",
                  "You are capable of more than a penguin in a birthday hat can imagine",
                  "You can’t change the direction of the wind, but you can become a balloon giraffe",
                  "The difference between ordinary and extraordinary is a tiger in a tutu",
                  "There’s no elevator to success, just a potato in a trench coat",
                  "Keep your face toward the sun, but don’t let the donuts steal your hat",
                  "Challenges are what make life spicy, like a taco surfing on a comet",
                  "Don’t be afraid to fail, just be afraid of the pancake on the ceiling",
                  "Life is 10 percent what happens to you and 90 percent how well you juggle flamingos",
                  "The only thing standing between you and your goal is a confused potato",
                  "Don’t be afraid to give up the good to chase a raccoon wearing a hat",
                  "Stay positive, even when the monkey steals your sandwich", 
                  "The best dreams happen when you’re a butterfly on a trampoline",
                  "Failure is just another step in your ladder made of marshmallows",
                  "Don’t let fear stop you from being a unicorn in a disco",
                  "You don’t have to be great to start, but you need at least one invisible banana",
                  "If you want to shine like the sun, be prepared to fry like an eggplant on Mars",
                  "The only way to achieve the impossible is to juggle three imaginary tacos",
                  "Push yourself, because no one else will push your jellyfish on a swing",
                  "Every champion was once a penguin who couldn’t open a peanut butter jar",
                  "To be successful, your passion must burn like a toaster on fire in a blizzard",
                  "Never give up on a dream just because a koala stole your sandwich",
                  "If you can dream it, you can build a house out of chocolate penguins",
                  "Believe you can and you’re halfway to a sandwich wearing a cape",
                  "Don’t be a prisoner of your past, become a waffle in a time machine",
                  "Success doesn’t happen overnight, unless you’re a kangaroo in a library",
                  "When one door closes, another opens to a room full of spaghetti",
                  "The biggest adventure is teaching a goldfish to ride a bicycle",
                  "Life begins at the end of your comfort zone, where the llamas dance",
                  "Keep moving forward, even if you’re on a treadmill made of jellybeans",
                  "Success is not the key to happiness, it’s a llama wearing a hat in the rain",
                  "Every accomplishment starts with a chicken on a skateboard", 
                  "You can’t go back and change the beginning, but you can make spaghetti dance",
                  "What lies behind us and what lies before us are pancakes on a trampoline",
                  "Don’t be afraid to give up the good to chase a banana in a top hat",
                  "Be so good they can’t ignore your glitter-filled nacho hat",
                  "Life is not about waiting for the storm to pass, it’s about juggling giraffes",
                  "You are stronger than you think, like a turtle driving a race car", 
                  "Do what you love, even if it’s being a taco on a pogo stick",
                  "Don’t stop until you’re a rainbow made of pizza and confetti",
                  "Be brave enough to color outside the noodles",
                  "Be the light that makes a penguin wear sunglasses in the dark",
                  "Life is what happens when you’re too busy chasing an invisible giraffe",
                  "In the end, we only regret the tacos we didn’t ride in a hot air balloon"
                ]
        attributees = ["Lieutenant-General Abraham D. Lincoln",
                       "Professor David T. Beckham",
                       "Dr Stephen H.W. Fry",
                       "Colonel Martin Van Luther",
                       "President George W. Clooney",
                       "Surgeon-General Katy J. Perry",
                       "Reverend Donald B. Trump",
                       "Sergeant Kamala de Harris",
                       "Rabbi George S. Windsor",
                       "Sir Harry S.T. Potter",
                       "Lord Samwise of Gamgee",
                       "Postmaster-General Margaret R.D. Thatcher",
                       "Sultan Horatio ibn Kitchener"]

        return quotes[rand_num], attributees[random.randrange(0,12)]
    

